#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

pat='(SE3-[0-9]*)'
s="$(git rev-parse --abbrev-ref HEAD)"

base=$(cat $1)
message=`echo ${base:0:1} | tr '[a-z]' '[A-Z]'`${base:1}

[[ $s =~ $pat ]]
BRANCH_NAME="["${BASH_REMATCH[0]}"]"
FULL_MESSAGE="${BRANCH_NAME} $message"

echo '' > $1
echo "$FULL_MESSAGE" $(cat "$1") > "$1"

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | 'vendor/bin/grumphp' 'git:commit-msg' '--ansi' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")
