name: PHP Composer

on:
  push:
    branches: [ your_branch ]
  pull_request:
    branches: [ your_branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/checkout@v2

    - name: configure php 8.0
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.0
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, exif, pcntl, gd, ext-zip

    - name: Install composer
      run: |
        composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
