name: Test
on:
  push:
    branches: ['your_branch']
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/coder-lifestyle/php-docker-image:main
      credentials:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Change Directory Ownership
        run: chown -R $(whoami) $(pwd)
      - name: install composer dependencies
        run: composer install --no-scripts --prefer-dist --no-ansi --no-interaction --no-progress
      - name: Prepare Symfony Application
        run: cp .env.ci .env
      - name: Run Database Migrations and Seeders
        run: touch ./database.sqlite && php bin/console doctrine:migrations:migrate && php bin/console doctrine:fixtures:load
      - name: Build UI
        run: npm install && npm run dev
      - name: Run Tests
        run: php bin/phpunit
      - name: Generate Code Coverage Report
        run: XDEBUG_MODE=coverage  bin/phpunit --coverage-html reports
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: reports/